### PR TITLE
Improved UI. Added copy to clipboard.

### PR DESCRIPTION
**Pull request by NistorCristian**
I've removed everything in `main.css` and only added what is necessary. 

I put a `link` tag in head that gets the https://status.im/css/main.min.css. There is no reason to have a totally different `.css` since it's going to be exactly the same overall.
I updated header and footer.
I've added copy to clipboard.

I'm going to need help with name extraction from the code.

### CODE REVIEW

**Comment by hesterbruikman** [comment]
@NistorCristian Sorry I missed this PR! Can you share a screenshot of the update?

**Comment by hesterbruikman** [comment]
@NistorCristian what are you running into extracting the (ENS) name from the code?
cc @Ferossgp

**Comment by NistorCristian** [comment]
@hesterbruikman I haven't touched that part. I honestly I have no idea how it was done. I only changed the style. A little bit of css, js and html. But just visual changes.

**Comment by Ferossgp** [comment]
@hesterbruikman Ens name is added to the link and automatically rendered correct. The part that should be done is to detect that the name is PublicKey and decode it as @jakubgs described https://github.com/status-im/universal-links-handler/issues/17#issuecomment-573628232

**Comment by hesterbruikman** [comment]
OK, I see. Thanks @Ferossgp! If ENS is settled, I think it's fine to leave detecting and converting the public key for now.

@NistorCristian Can you take a look at the specs by @errorists in this comment? https://github.com/status-im/universal-links-handler/issues/17#issuecomment-573629801
As well as the design file on [Figma ](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=2869%3A23223)

I think I'm missing:
- Responsiveness. `Open in Status` but moves next to the QR code on desktop.
- Button should say `Download Status`
- Grey subtext below button. With ENS name: `Chat and transact with <name>` or with PublicKey: `Chat and transact with this user`
- UI element to copy name or PublicKey
- Button to Open in Status app if page is open on Mobile and Status is installed

Dapps View


Please let me know if you run into any issues with that!

**Comment by NistorCristian** [comment]
Hey @hesterbruikman ,

This is what I see:
png 1

I'll need help with 2 things.

1) How can I detect if Status is installed or not?
2) I don't know how to extract the name from that key.

But in terms of styling looks pretty close.

cc. @j-zerah

**Comment by jakubgs** [comment]
I explained how the usernames are generated in https://github.com/status-im/universal-links-handler/issues/17#issuecomment-573628232. If you don't think you can handle that I can try creating a JS library that does this.

**Comment by hesterbruikman** [comment]
Thanks @NistorCristian! Looks great. Am I right that if the url you get from Status includes an ENS name https://get.status.im/user/hester, the name would be shown instead of the key?

As I understand it, the issue #2 you describe is in the case the url only comes with the key, is that right? (e.g. https://get.status.im/user/0x04f1ab965a3db6433923ceba0488ff605f230aca4c4c93bb6563c10b700cfdbbed2a364c980b9cf9679f352584d4da44cc01fc1e7257f1d2b80ffff5af64aa129f)

**Comment by hesterbruikman** [comment]
For the case in which Status is installed, I suggest we separate it out in a new issue. The representation with ENS name if available has priority.

**Comment by NistorCristian** [comment]
> I explained how the usernames are generated in [#17 (comment)](https://github.com/status-im/universal-links-handler/issues/17#issuecomment-573628232). If you don't think you can handle that I can try creating a JS library that does this.

I don't think I can handle this. I have 6 active projects right now so I simply can't do this too, unfortunately. Besides this everything should be done for now.

**Comment by jakubgs** [comment]
Okay @NistorCristian, I'll try making a library for that tomorrow. Will ping you when its done.

**Comment by jakubgs** [comment]
I have created a JS library for converting Chat keys to Chat names:
https://github.com/status-im/js-status-chat-name
Feel free to play with `v0.1.1`. If you see any issues or have any comments tell me.

**Comment by hesterbruikman** [comment]
@nistorchristian can you confirm that ENS name is shown when url from Status provides it?

If so, I suggest to merge these changes and I'll create another issue for converting the key to random name.

Cc @ferossgp in case you can confirm

**Comment by Ferossgp** [comment]
@hesterbruikman Yes, ens name are shown correctly

**Pull request merged**
