### PR TITLE
redirect to referral service if invite code is set

### PR DESCRIPTION
**Pull request by jakubgs**
This should redirect using the JS fallback to `https://test-referral.status.im/${invite}` if the `invite` parameter is set.

Once https://get.status.im/ is up - prod of referral service - I'll change this PR to use that.

### CODE REVIEW

**Comment by jakubgs** [comment]
@Ferossgp should this be merged or have we changed anything while this was hanging around?

**Comment by jakubgs** [comment]
Updated the Referral Service URL to use https://get.status.im/.

**Comment by hesterbruikman** [comment]
@andremedeiros do you think this one is still necessary?

**Comment by hesterbruikman** [comment]
@jakubgs, I think this should still be merged indeed. Currently seeing invite code on join.status.im. Can open Play store to download and install Status, but invite code is lost along the way. If I understand this correctly. Redirect to referral service should return `play.goo.gl` link with invite code

What I don't know is how the referral service will handle this redirect. Will see what I can find, but would appreciate if you can also take a look @jakubgs 

cc @Serhy

**Comment by jakubgs** [comment]
I have deployed this to our links handler.

**Pull request merged**
